### ISSUE TITLE
Cool project! Would love to contribute

### ISSUE THREAD

**Issue by tropicalchancer** [rignaneseleo/groups-for-nomads#4]
Hey there, just wanted to spot by and say this project is lovely! 

I went to shoot you a DM on twitter to say hi but no option to DM. Here's my twitter if you want to chat about this project: https://twitter.com/chancecollabs 

Best, 

Chance

**Comment by joshxplore** [comment]
Hey there :)
If you'd like to contribute just write me on instagram @joshxplore since i dont have twitter.
Cheers!
